version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: bash -c 'python3 taskmanager/manage.py makemigrations && taskmanager/manage.py migrate && taskmanager/manage.py runserver 0.0.0.0:5000'
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    depends_on:
      - db